languageCode = "en-us"
title = "CAnderskov - Notes To Self."
baseurl = "https://canderskov.github.io/"
theme = "hugo-redlounge"

[params]
    sidebartitle = "Canderskov"
    sidebartagline = "Notes to self"
    #sidebarphoto = "/img/photo.png"


[[menu.main]]
    name = "Posts"
    url = "/post"